# Generated by Django 2.2.11 on 2021-07-03 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('PersonnelCode', models.CharField(max_length=100, verbose_name='شماره پرسنلی')),
                ('PeriodName', models.CharField(max_length=100, verbose_name='نام شیفت')),
                ('OrganizationName', models.CharField(max_length=100, verbose_name='نام اداره')),
                ('DayStatus', models.CharField(max_length=50, verbose_name='حالت روز')),
                ('Date', models.DateField(verbose_name='تاریخ')),
                ('Login1', models.TimeField(verbose_name='ورود 1')),
                ('Login2', models.TimeField(verbose_name='ورود 2')),
                ('Login3', models.TimeField(verbose_name='ورود 3')),
                ('Logout1', models.TimeField(verbose_name='خروج 1')),
                ('Logout2', models.TimeField(verbose_name='خروج 2')),
                ('Logout3', models.TimeField(verbose_name='خروج 3')),
                ('TimeSpent', models.TimeField(verbose_name='کارکرد')),
                ('LoginDelay', models.TimeField(verbose_name='تاخیر ورود')),
                ('LogoutRush', models.TimeField(verbose_name='تعجیل خروج')),
                ('WorkDeduction', models.TimeField(verbose_name='کسرکار')),
                ('OvertimeLogin', models.TimeField(verbose_name='اضافه کار ورود')),
                ('OvertimeLogout', models.TimeField(verbose_name='اضافه کار خروج')),
                ('TotalOvertime', models.TimeField(verbose_name='اضافه کار کل')),
                ('Transportation', models.TimeField(verbose_name='ایاب ذهاب')),
                ('HourlyLeave', models.TimeField(verbose_name='مرخصی ساعتی')),
                ('HourlyMission', models.TimeField(verbose_name='ماموریت ساعتی')),
                ('RoofOvertimeRemained', models.TimeField(verbose_name='مانده سقف')),
                ('IdUsers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='شناسه کاربر')),
            ],
            options={
                'verbose_name': 'کارکرد پرسنل',
                'verbose_name_plural': 'کارکرد پرسنل',
            },
        ),
    ]
