# Generated by Django 2.2.11 on 2021-04-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0012_auto_20210426_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCommodity',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='کد دسته')),
                ('Name', models.CharField(max_length=100, verbose_name='نام دسته')),
            ],
            options={
                'verbose_name': 'دسته',
                'verbose_name_plural': 'دسته ها',
            },
        ),
        migrations.CreateModel(
            name='GroupCommodity',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='کد گروه')),
                ('Name', models.CharField(max_length=100, verbose_name='نام گروه')),
            ],
            options={
                'verbose_name': 'گروه',
                'verbose_name_plural': 'گروه\u200f ها',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='کد تامین کننده')),
                ('Name', models.CharField(max_length=100, verbose_name='نام تامین کننده')),
            ],
            options={
                'verbose_name': 'تامین کننده',
                'verbose_name_plural': 'تامین کننده ها',
            },
        ),
        migrations.CreateModel(
            name='UnitofMeasurement',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='کدواحد سنجش')),
                ('Name', models.CharField(max_length=100, verbose_name='نام واحد سنجش')),
            ],
            options={
                'verbose_name': 'واحد سنجش',
                'verbose_name_plural': 'واحدهای سنجش',
            },
        ),
        migrations.CreateModel(
            name='UnitPack',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='کد بسته')),
                ('Name', models.CharField(max_length=100, verbose_name='نام بسته')),
            ],
            options={
                'verbose_name': 'بسته',
                'verbose_name_plural': 'بسته ها',
            },
        ),
        migrations.CreateModel(
            name='Storeroom',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='کدانبار')),
                ('Name', models.CharField(max_length=100, verbose_name='نام انبار')),
                ('Address', models.TextField(verbose_name='آدرس انبار')),
                ('IdCity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.City', verbose_name='شهرستان')),
            ],
            options={
                'verbose_name': 'انبار',
                'verbose_name_plural': 'انبار ها',
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='کد کالا')),
                ('Name', models.CharField(max_length=100, verbose_name='نام کالا')),
                ('UnitPackCount', models.IntegerField(verbose_name='مقدار بسته')),
                ('CommoditySpecifications', models.TextField(verbose_name='مشخصات کالا')),
                ('ExpirationDate', models.DateField(verbose_name='تاریخ مصرف')),
                ('OrderPoint', models.IntegerField(verbose_name='نقطه سفارش')),
                ('MinimumInventory', models.IntegerField(verbose_name='حداقل موجودی')),
                ('OrderAmount', models.IntegerField(verbose_name='میزان سفارش')),
                ('MaximumInventory', models.IntegerField(verbose_name='حداکثر موجودی')),
                ('AddressCommodity', models.TextField(verbose_name='آدرس کالا')),
                ('TechnicalNumber', models.CharField(max_length=100, verbose_name='شماره فنی')),
                ('BarCodeText', models.CharField(max_length=255, verbose_name='بارکد')),
                ('BarCodeImage', models.CharField(max_length=255, verbose_name='بارکد')),
                ('TechnicalSpecifications', models.TextField(verbose_name='مشخصات فنی')),
                ('EntryDateTime', models.DateTimeField(auto_now=True)),
                ('UnitPrice', models.IntegerField(verbose_name='بهای واحد')),
                ('IdCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.CategoryCommodity', verbose_name='شناسه دسته ')),
                ('IdGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.GroupCommodity', verbose_name='شناسه گروه ')),
                ('IdStoreroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Storeroom', verbose_name='شناسه انبار ')),
                ('IdSupplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Supplier', verbose_name='شناسه تامین کننده ')),
                ('IdUnitPack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.UnitPack', verbose_name='شناسه بسته ')),
                ('IdUnitofMeasurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.UnitofMeasurement', verbose_name='کد واحد سنجش')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالا ها',
            },
        ),
    ]
