# Generated by Django 2.2.11 on 2021-04-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeroom',
            name='status',
            field=models.CharField(choices=[('A', 'فعال'), ('N', 'غیرفعال')], default='A', max_length=1, verbose_name='وضعیت'),
        ),
    ]
