# Generated by Django 2.2.11 on 2021-05-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210518_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Telephone',
            new_name='TelephoneCustomer',
        ),
        migrations.AlterField(
            model_name='storeroom',
            name='Telephone',
            field=models.TextField(verbose_name='شماره تلفن'),
        ),
    ]
