# Generated by Django 2.2.11 on 2021-05-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210519_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='EconomicNumber',
            field=models.CharField(max_length=20, verbose_name='کدملی/شماره اقتصادی'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Family',
            field=models.CharField(max_length=200, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='FirstBalanceCourse',
            field=models.IntegerField(verbose_name='مانده اول دوره'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Mobile',
            field=models.CharField(max_length=10, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='NationalID',
            field=models.CharField(max_length=20, verbose_name='شناسه ملی'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='PostalCode',
            field=models.CharField(max_length=10, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='RegistrationNumber',
            field=models.CharField(max_length=20, verbose_name='شماره ثبت'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='TelephoneCustomer',
            field=models.CharField(max_length=15, verbose_name='شماره تلفن'),
        ),
    ]
