# Generated by Django 2.2.11 on 2021-05-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210520_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Status',
            field=models.CharField(choices=[('A', 'بی حساب'), ('B', 'بدهکار'), ('C', 'بستانکار')], default='A', max_length=1, verbose_name='وضعیت حساب'),
        ),
    ]
