# Generated by Django 2.2.11 on 2021-05-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='Description',
            field=models.TextField(default='', verbose_name='توضیحات'),
        ),
    ]
