# Generated by Django 2.2.11 on 2021-05-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_commodity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeroom',
            name='Telephone',
            field=models.CharField(max_length=10, verbose_name='شماره تلفن'),
        ),
    ]
