# Generated by Django 2.2.11 on 2021-05-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_entrycommodity_entrycommoditycreate_entrycommodityupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrycommodity',
            name='InvoiceNumber',
            field=models.CharField(default='1', max_length=200, verbose_name='شماره فاکتور'),
        ),
    ]
