# Generated by Django 2.2.11 on 2021-06-10 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20210610_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='IdEntryCommodity',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='inventory.EntryCommodity', verbose_name='ورود کالا'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drivers',
            name='Family',
            field=models.CharField(max_length=100, verbose_name='نام خانوادگی'),
        ),
    ]
