# Generated by Django 2.2.11 on 2021-06-11 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_changed_my_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrycommodity',
            name='Status',
            field=models.CharField(choices=[('i', 'ورود'), ('o', 'خروج'), ('r', 'مرجوعی')], default='i', max_length=1, verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='productRepaired',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='کد تعمیر')),
                ('SerialNumber', models.CharField(max_length=200, verbose_name='سریال کالا')),
                ('DateRegistration', models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت')),
                ('DateDelivery', models.DateTimeField(auto_now=True, verbose_name='تاریخ تحویل')),
                ('Description', models.TextField(max_length=200, verbose_name='توضیحات')),
                ('IdCommodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Commodity', verbose_name='نام کالا')),
                ('IdCustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Customer', verbose_name='نام مشتری')),
            ],
            options={
                'verbose_name': 'تعمیر کالا',
                'verbose_name_plural': 'تعمیر کالا',
            },
        ),
    ]
