# Generated by Django 2.2.11 on 2021-06-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20210611_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productrepaired',
            options={'verbose_name': 'تعمیر کالا', 'verbose_name_plural': 'تعمیر کالاها'},
        ),
        migrations.AlterField(
            model_name='productrepaired',
            name='DateDelivery',
            field=models.DateTimeField(verbose_name='تاریخ تحویل'),
        ),
        migrations.AlterField(
            model_name='productrepaired',
            name='DateRegistration',
            field=models.DateTimeField(verbose_name='تاریخ ثبت'),
        ),
    ]
