# Generated by Django 2.2.11 on 2021-06-15 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementArrived',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='شماره سند')),
                ('Type', models.CharField(choices=[('C', 'نقدی'), ('I', 'قسطی')], max_length=1, verbose_name='نوع')),
                ('Date', models.DateTimeField(auto_now=True, verbose_name='تاریخ سند')),
                ('Amount', models.IntegerField(verbose_name='مبلغ')),
                ('Description', models.TextField(max_length=200, verbose_name='توضیحات')),
                ('Address', models.TextField(max_length=200, verbose_name='آدرس')),
                ('Telephone', models.CharField(max_length=10, verbose_name='تلفن')),
                ('ReceiptNumber', models.CharField(choices=[('C', 'نقدی'), ('I', 'قسطی')], max_length=20, verbose_name='شماره سند')),
            ],
            options={
                'verbose_name': 'تسویه فاکتور',
                'verbose_name_plural': 'تسویه فاکتورها',
            },
        ),
        migrations.AddField(
            model_name='receipt',
            name='IdCustomer',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='inventory.Customer', verbose_name='نام مشتری'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='Type',
            field=models.CharField(choices=[('B', 'خرید'), ('S', 'فروش')], default=7, max_length=1, verbose_name='نوع'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commodity',
            name='Description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
    ]
