# Generated by Django 2.2.11 on 2021-06-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_changed_my_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlementarrived',
            name='Address',
            field=models.CharField(max_length=200, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='settlementarrived',
            name='ReceiptNumber',
            field=models.CharField(max_length=20, verbose_name='شماره سند'),
        ),
    ]
