# Generated by Django 2.2.11 on 2021-06-17 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20210617_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='IdStoreroom',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='inventory.Storeroom', verbose_name='نام انبار'),
            preserve_default=False,
        ),
    ]
