# Generated by Django 2.2.11 on 2021-06-17 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_receipt_idstoreroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='IdStoreroom',
            field=models.ForeignKey(default=29, on_delete=django.db.models.deletion.CASCADE, to='inventory.Storeroom', verbose_name='نام انبار'),
        ),
    ]
