# Generated by Django 2.2.11 on 2021-06-17 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_auto_20210617_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementarrived',
            name='IdStoreroom',
            field=models.ForeignKey(default=29, on_delete=django.db.models.deletion.CASCADE, to='inventory.Storeroom', verbose_name='نام انبار'),
        ),
    ]
