# Generated by Django 2.2.11 on 2021-06-17 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_settlementarrived_idstoreroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='IdStoreroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Storeroom', verbose_name='نام انبار'),
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='شماره سند')),
                ('Count', models.IntegerField(verbose_name='تعداد')),
                ('DateRequired', models.DateTimeField(auto_now=True, verbose_name='تاریخ نیاز')),
                ('Date', models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت')),
                ('TechnicalSpecifications', models.TextField(max_length=200, verbose_name='مشخصات فنی')),
                ('PurchaseSource', models.CharField(max_length=20, verbose_name='منبع خرید')),
                ('PurchasingOfficer', models.CharField(max_length=20, verbose_name='مامور خرید')),
                ('IdCommodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Commodity', verbose_name='نام کالا')),
                ('IdStoreroom', models.ForeignKey(default=29, on_delete=django.db.models.deletion.CASCADE, to='inventory.Storeroom', verbose_name='نام انبار')),
                ('IdUnitofMeasurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.UnitofMeasurement', verbose_name='واحد سنجش')),
            ],
            options={
                'verbose_name': 'درخواست خرید',
                'verbose_name_plural': 'درخواست های خرید',
            },
        ),
    ]
