# Generated by Django 2.2.11 on 2021-06-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_auto_20210617_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='DateRequired',
            field=models.DateTimeField(verbose_name='تاریخ نیاز'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='شماره درخواست'),
        ),
    ]
