# Generated by Django 2.2.11 on 2021-07-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_auto_20210708_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasingOfficer',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='شناسه مامور خرید')),
                ('Name', models.CharField(max_length=100, verbose_name='نام')),
                ('Family', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('Mobile', models.CharField(max_length=10, verbose_name='شماره موبایل')),
                ('TelephoneCustomer', models.CharField(max_length=15, verbose_name='شماره تلفن')),
                ('NationalID', models.CharField(max_length=20, verbose_name='شناسه ملی')),
                ('PostalCode', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('Address', models.TextField(verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'تسویه فاکتور',
                'verbose_name_plural': 'تسویه فاکتورها',
            },
        ),
    ]
