# Generated by Django 2.2.11 on 2021-07-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_purchasingofficer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchasingOfficer',
        ),
    ]
