# Generated by Django 2.2.11 on 2021-07-09 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_delete_purchasingofficer'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='Status',
            field=models.CharField(choices=[('Y', 'خرید شده'), ('N', 'خرید نشده')], default='N', max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='IdStoreroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Storeroom', verbose_name='نام انبار'),
        ),
    ]
