# Generated by Django 2.2.11 on 2021-07-12 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_auto_20210710_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='TotalAmount',
        ),
    ]
