# Generated by Django 2.2.11 on 2021-07-13 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_auto_20210712_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrepaired',
            name='IdStoreroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.Storeroom', verbose_name='نام انبار'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productrepaired',
            name='DateRegistration',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت'),
        ),
    ]
