# Generated by Django 2.2.11 on 2021-07-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_auto_20210713_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfersbetweenstoreroom',
            options={'verbose_name': 'شناسه انتقال', 'verbose_name_plural': 'نقل و انتقال'},
        ),
        migrations.AlterField(
            model_name='transportation',
            name='Sender',
            field=models.CharField(max_length=200, verbose_name='فرستنده'),
        ),
    ]
